# Generated by Django 5.0.7 on 2024-07-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snippet",
            old_name="lineos",
            new_name="linenos",
        ),
    ]
